import 'dart:async';

import 'package:csv/csv.dart';
import 'package:flutter/services.dart' show rootBundle;

/// Loads NZFCC category metadata and exposes emoji helpers for budget rows.
class CategoryEmojiHelper {
  CategoryEmojiHelper._(this._categoryGroups);

  final Map<String, String> _categoryGroups;

  static CategoryEmojiHelper? _instance;

  static const String defaultEmoji = '💸';
  static const String uncategorizedEmoji = '❓';

  static const Map<String, String> _groupEmoji = {
    'Food': '🍽️',
    'Transport': '🚗',
    'Lifestyle': '🎉',
    'Appearance': '👗',
    'Household': '🏠',
    'Professional Services': '💼',
    'Education': '📚',
    'Health': '⚕️',
    'Utilities': '⚡',
    'Housing': '🏡',
  };

  /// Per-category emoji keyed by lowercased NZFCC category name.
  static const Map<String, String> _categoryEmoji = {
    // ── Food ──
    'bakeries': '🥐',
    'convenience stores': '🏪',
    'fish and seafood supplies': '🐟',
    'ice cream, gelato, nut, and confectionary stores': '🍦',
    'meal kit stores': '🥘',
    'meat supplies': '🥩',
    'specialty food stores': '🧀',
    'supermarkets and grocery stores': '🛒',

    // ── Transport ──
    'automotive body repair and painting services': '🔧',
    'automotive parts and accessories': '⚙️',
    'automotive repair and servicing': '🛠️',
    'bicycle stores, rentals, and repairs': '🚲',
    'boat transport services': '⛴️',
    'bus and shuttle transport services': '🚌',
    'car and motorcycle rentals': '🚗',
    'car, truck, and motorcycle dealers': '🚘',
    'electric vehicle charging services': '🔌',
    'fuel stations': '⛽',
    'parking services': '🅿️',
    'taxi, rideshare, and on-demand transport services': '🚕',
    'toll fees': '🛣️',
    'towing services': '🚛',
    'train and rail transport services': '🚆',
    'transport services (not elsewhere classified)': '🚐',
    'truck, trailer, machinery, and equipment rentals': '🚚',
    'tyre stores': '🛞',
    'vehicle dealers (not elsewhere classified)': '🚙',

    // ── Housing ──
    'body corporate': '🏢',
    'local government': '🏛️',
    'rent for permanent accommodation': '🏠',
    'retirement accommodation': '🏡',

    // ── Utilities ──
    'electricity and gas services': '⚡',
    'electricity services': '💡',
    'gas services': '🔥',
    'internet services': '🌐',
    'telecommunication services': '📱',
    'water and sanitation services': '💧',

    // ── Health ──
    'chiropodists and podiatrists': '🦶',
    'chiropractors and osteopaths': '🦴',
    'dental and medical laboratories': '🔬',
    'dental services': '🦷',
    'doctors and physicians': '🩺',
    'gyms, fitness, aquatic facilities, yoga, pilates': '💪',
    'hospices': '🏥',
    'hospitals and emergency care': '🚑',
    'medical products and supplies (not elsewhere classified)': '💊',
    'medical services (not elsewhere classified)': '⚕️',
    'optometrists and eyewear': '👓',
    'pharmacies': '💊',
    'physiotherapy and massage therapy': '💆',
    'psychology, psychiatric, counselling, and other mental health services':
        '🧠',
    'sports and athletic clubs': '🏅',
    'veterinary services': '🐾',

    // ── Education ──
    'book stores': '📖',
    'childcare services': '👶',
    'education (not elsewhere classified)': '📚',
    'libraries': '📕',
    'newspapers, magazines, and literary subscriptions': '📰',
    'performing art training': '🎭',
    'primary and secondary schools': '🏫',
    'universities, professional schools, and other tertiary education': '🎓',

    // ── Appearance ──
    'apparel and accessory stores': '👗',
    'child and infant clothing': '🧒',
    'clothing alteration and repair': '✂️',
    'clothing rental': '👔',
    'clothing stores': '👕',
    'cosmetic supplies': '💄',
    'fabric, sewing, knitting, and related supplies': '🧵',
    'haircuts and treatments': '💇',
    'secondhand and opportunity stores': '♻️',
    'shoe stores': '👟',
    'uniforms and commercial clothing': '👔',
    'watch, clock, and jewellery stores and services': '💎',

    // ── Lifestyle ──
    'air transport services': '✈️',
    'airports': '🛫',
    'art and craft supplies': '🎨',
    'art stores, dealers, and galleries': '🖼️',
    'attractions, museums, zoos, amusement parks, circuses, exhibits': '🎢',
    'bars, pubs, nightclubs': '🍺',
    'boat dealers': '⛵',
    'boat rentals': '🚤',
    'cafes and restaurants': '☕',
    'cash withdrawals': '🏧',
    'casino, lottery, and other gambling services': '🎰',
    'caterers': '🍽️',
    'cigarette, vape, and other smoking products': '🚬',
    'cinemas': '🎬',
    'cosmetic, health spas, and relaxation massage services': '🧖',
    'dating and matchmaking services': '💕',
    'digital gaming products and services': '🎮',
    'duty free stores': '🛍️',
    'entertainment (not elsewhere classified)': '🎭',
    'events and tickets (not elsewhere classified)': '🎫',
    'fast food stores': '🍔',
    'floral supplies and services': '💐',
    'gift and souvenir stores': '🎁',
    'golf courses': '⛳',
    'hobby, toy, and physical game stores': '🧩',
    'hotels, motels, and other temporary accommodation': '🏨',
    'liquor stores': '🍷',
    'marinas, marine supplies, and marine services': '⚓',
    'media and entertainment streaming services': '📺',
    'motor parks, campgrounds, holiday parks, recreational camps': '⛺',
    'musical equipment, recordings, and supplies': '🎵',
    'photography equipment and services': '📷',
    'sports equipment and supplies': '⚽',
    'theatre, concerts, and other artistic performances': '🎶',
    'travel agencies and tour operators': '🧳',
    'welfare and charity': '❤️',
    'wineries, breweries, and distilleries': '🍇',

    // ── Household ──
    'agricultural supplies': '🌾',
    'antique stores and repair': '🏺',
    'appliance and furniture rentals': '🛋️',
    'appliance repair and services': '🔧',
    'building and carpentry services': '🔨',
    'building supplies': '🧱',
    'chemical products and services': '🧪',
    'child support': '👶',
    'cleaning, sanitation, and pest control services': '🧹',
    'computer equipment': '💻',
    'concrete services': '🏗️',
    'consumer electronics repair and services': '🔌',
    'curtains, blinds, and window coverings': '🪟',
    'electrical supplies and services': '🔌',
    'electronic and appliance stores': '🖥️',
    'fireplaces and supplies': '🔥',
    'floor covering stores': '🪵',
    'general retail stores': '🏬',
    'hardware equipment and supplies': '🔩',
    'heating, cooling, and ventilation equipment and services': '❄️',
    'home furnishing and repair stores': '🛋️',
    'industrial and commercial supplies (not elsewhere classified)': '🏭',
    'insurance': '🛡️',
    'landscaping, garden, and horticultural services': '🌿',
    'laundry and drycleaning': '🧺',
    'nurseries and garden supplies': '🌱',
    'painting supplies and services': '🎨',
    'pets and related supplies, accommodation, and services': '🐾',
    'plumbing and gasfitting supplies and services': '🚿',
    'repair and servicing (not elsewhere classified)': '🔧',
    'roofing services': '🏠',
    'shoe and leather repair, keycutting, or engraving': '🔑',
    'specialty retail stores (not elsewhere classified)': '🛍️',
    'stationery and office supplies': '✏️',
    'storage facilities': '📦',
    'swimming pools, supplies, and services': '🏊',
    'trade services (not elsewhere classified)': '🔧',
    'variety stores': '🏬',
    'waste and recycling services': '♻️',
    'welding, fabrication, and metal services': '⚙️',

    // ── Professional Services ──
    'accountancy, bookkeeping, auditing, and tax services': '📊',
    'advertising and marketing services': '📣',
    'architect, engineering, and surveying services': '📐',
    'business services (not elsewhere classified)': '💼',
    'business software and cloud services': '☁️',
    'courier and freight delivery services': '📦',
    'debt repayments': '💳',
    'employment and career services': '👔',
    'event venue and equipment rental': '🎪',
    'financial advice and wealth management': '📈',
    'financial asset brokers, exchanges, and managed funds': '📈',
    'financial services (not elsewhere classified)': '🏦',
    'foreign exchange and money transfer services': '💱',
    'funeral, death, and memorial services': '🕊️',
    'it and software development services': '💻',
    'legal services': '⚖️',
    'lending services': '🏦',
    'management consulting': '📋',
    'membership organisations (not elsewhere classified)': '🤝',
    'national government services': '🏛️',
    'personal software (not elsewhere classified)': '📱',
    'political organisations': '🗳️',
    'postal services': '📮',
    'printing, publishing, and signmaking services': '🖨️',
    'professional services (not elsewhere classified)': '💼',
    'real estate services': '🏘️',
    'religious organisations': '⛪',
    'security stores and services': '🔒',
    'tax payments': '🧾',
    'testing laboratories (non medical)': '🔬',
  };

  static Future<CategoryEmojiHelper> ensureLoaded() async {
    if (_instance != null) return _instance!;

    final csvRaw = await rootBundle.loadString(
      'assets/data/nzfcc_categories.csv',
    );
    final rows = const CsvToListConverter(
      eol: '\n',
      shouldParseNumbers: false,
    ).convert(csvRaw);

    final map = <String, String>{};
    for (final row in rows.skip(1)) {
      if (row.length < 3) continue;
      final name = '${row[1]}'.trim();
      final group = '${row[2]}'.trim();
      if (name.isEmpty || group.isEmpty) continue;
      map[name.toLowerCase()] = group;
    }

    _instance = CategoryEmojiHelper._(map);
    return _instance!;
  }

  String emojiForName(String? rawName) {
    if (rawName == null || rawName.trim().isEmpty) {
      return defaultEmoji;
    }
    final normalized = rawName.trim().toLowerCase();

    final specific = _categoryEmoji[normalized];
    if (specific != null) return specific;

    final group = _categoryGroups[normalized];
    if (group != null) {
      return _groupEmoji[group] ?? defaultEmoji;
    }

    return _emojiFromText(rawName);
  }

  static const Map<String, List<String>> _groupKeywords = {
    'Food': [
      'grocery',
      'supermarket',
      'bakery',
      'bakeries',
      'meat',
      'seafood',
      'fish',
      'food',
      'restaurant',
      'cafe',
      'convenience store',
      'ice cream',
      'gelato',
      'confectionary',
      'meal kit',
      'specialty food',
    ],
    'Transport': [
      'transport',
      'fuel',
      'taxi',
      'rideshare',
      'bus',
      'shuttle',
      'train',
      'rail',
      'automotive',
      'car dealer',
      'motorcycle',
      'vehicle',
      'parking',
      'toll',
      'towing',
      'tyre',
      'tire',
      'bicycle',
      'electric vehicle',
      'ev charg',
      'truck',
      'trailer',
      'boat transport',
    ],
    'Housing': [
      'rent',
      'housing',
      'mortgage',
      'body corporate',
      'local government',
      'council',
      'rates',
      'retirement accommodation',
    ],
    'Utilities': [
      'utility',
      'utilities',
      'electric',
      'power',
      'gas service',
      'internet',
      'water',
      'sanitation',
      'telecom',
      'broadband',
      'fibre',
      'fiber',
    ],
    'Health': [
      'health',
      'doctor',
      'medical',
      'pharmacy',
      'pharmacies',
      'gym',
      'fitness',
      'yoga',
      'pilates',
      'aquatic',
      'dental',
      'dentist',
      'chiropract',
      'osteopath',
      'chiropod',
      'podiatrist',
      'optometrist',
      'eyewear',
      'hospital',
      'emergency care',
      'hospice',
      'physiotherapy',
      'massage therapy',
      'psycholog',
      'psychiatr',
      'counselling',
      'mental health',
      'veterinar',
      'sports club',
      'athletic club',
    ],
    'Education': [
      'education',
      'school',
      'book store',
      'bookstore',
      'library',
      'libraries',
      'childcare',
      'daycare',
      'university',
      'tertiary',
      'newspaper',
      'magazine',
      'performing art',
      'tuition',
      'course',
      'training',
    ],
    'Appearance': [
      'appearance',
      'clothing',
      'apparel',
      'accessory',
      'shoe store',
      'footwear',
      'cosmetic',
      'fabric',
      'sewing',
      'knitting',
      'haircut',
      'hair treatment',
      'salon',
      'hair',
      'barber',
      'secondhand',
      'opportunity store',
      'op shop',
      'uniform',
      'jewellery',
      'jewelry',
      'watch store',
      'clothing rental',
      'clothing alteration',
    ],
    'Lifestyle': [
      'lifestyle',
      'entertainment',
      'travel',
      'holiday',
      'hotel',
      'motel',
      'accommodation',
      'bar',
      'pub',
      'nightclub',
      'cinema',
      'movie',
      'casino',
      'lottery',
      'gambling',
      'gaming',
      'caterer',
      'catering',
      'dating',
      'duty free',
      'gift',
      'souvenir',
      'golf',
      'hobby',
      'toy',
      'art store',
      'gallery',
      'museum',
      'zoo',
      'amusement',
      'attraction',
      'circus',
      'fast food',
      'takeaway',
      'floral',
      'florist',
      'flower',
      'liquor',
      'wine',
      'brewery',
      'distillery',
      'marina',
      'marine',
      'media streaming',
      'streaming',
      'netflix',
      'spotify',
      'campground',
      'holiday park',
      'motor park',
      'musical',
      'photography',
      'sports equipment',
      'concert',
      'theatre',
      'theater',
      'performance',
      'welfare',
      'charity',
      'donation',
      'cigarette',
      'vape',
      'smoking',
      'cash withdrawal',
      'atm',
      'boat dealer',
      'boat rental',
      'spa',
      'relaxation',
      'air transport',
      'airport',
      'flight',
      'airline',
      'tour operator',
      'travel agent',
    ],
    'Household': [
      'household',
      'home',
      'furnish',
      'garden',
      'insurance',
      'pet',
      'appliance',
      'furniture',
      'hardware',
      'building supply',
      'building supplies',
      'carpentry',
      'chemical',
      'cleaning',
      'pest control',
      'computer',
      'concrete',
      'curtain',
      'blind',
      'electronic store',
      'floor covering',
      'fireplace',
      'general retail',
      'heating',
      'cooling',
      'ventilation',
      'industrial',
      'landscape',
      'horticult',
      'laundry',
      'drycleaning',
      'dry cleaning',
      'nursery',
      'painting',
      'plumbing',
      'gasfitting',
      'repair',
      'roofing',
      'stationery',
      'office supply',
      'office supplies',
      'storage facilit',
      'swimming pool',
      'trade service',
      'variety store',
      'waste',
      'recycling',
      'welding',
      'fabrication',
      'metal service',
      'child support',
      'agricultural',
      'antique',
    ],
    'Professional Services': [
      'professional',
      'accountan',
      'bookkeeping',
      'auditing',
      'tax',
      'legal',
      'lawyer',
      'solicitor',
      'advertising',
      'marketing',
      'architect',
      'engineering',
      'surveying',
      'business service',
      'cloud service',
      'software service',
      'courier',
      'freight',
      'delivery',
      'employment',
      'career',
      'event venue',
      'financial',
      'foreign exchange',
      'money transfer',
      'funeral',
      'memorial',
      'it service',
      'software development',
      'lending',
      'loan',
      'debt repay',
      'management consult',
      'consulting',
      'membership',
      'government',
      'personal software',
      'political',
      'postal',
      'printing',
      'publishing',
      'signmak',
      'real estate',
      'property',
      'religious',
      'church',
      'security',
    ],
  };

  String _emojiFromText(String text) {
    final lower = text.toLowerCase();
    for (final entry in _groupKeywords.entries) {
      if (_containsAny(lower, entry.value)) {
        return _groupEmoji[entry.key] ?? defaultEmoji;
      }
    }
    return defaultEmoji;
  }

  static bool _containsAny(String input, List<String> needles) =>
      needles.any(input.contains);
}
